# Generated by Django 5.0 on 2023-12-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='_type',
            field=models.CharField(choices=[('top', 'Top'), ('wtv', 'Worth to visit')], max_length=3, null=True),
        ),
    ]
