# Generated by Django 5.0 on 2023-12-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0002_company__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='_type',
            field=models.CharField(choices=[('df', 'Default'), ('top', 'Top'), ('wtv', 'Worth to visit')], default='df', max_length=3, null=True),
        ),
    ]
